
// ACTIONS FOR LISTS
export const OPEN_LIST_MODAL = 'OPEN_LIST_MODAL'
export const CLOSE_LIST_MODAL = 'CLOSE_LIST_MODAL'
export const CHANGE_LIST_MODAL_NAME = 'CHANGE_LIST_MODAL_NAME'
export const RESET_LIST_MODAL_NAME = 'RESET_LIST_MODAL_NAME'
export const ADD_NEW_LIST = 'ADD_NEW_LIST'
export const DELETE_LIST = 'DELETE_LIST'
export const EDIT_LIST = 'EDIT_LIST'
export const SET_EDIT_LIST = 'SET_EDIT_LIST'
export const SET_SELECTED_LIST = 'SET_SELECTED_LIST'

// ACTIONS FOR SNIPPETS
export const CHANGE_SNIPPET_NAME = 'CHANGE_SNIPPET_NAME'
export const CHANGE_SNIPPET_CODE = 'CHANGE_SNIPPET_CODE'
export const CHANGE_SNIPPET_LIST = 'CHANGE_SNIPPET_LIST'
export const CHANGE_SNIPPET_LANGUAGE = 'CHANGE_SNIPPET_LANGUAGE'
export const ADD_NEW_SNIPPET = 'ADD_NEW_SNIPPET'
export const SET_SELECTED_SNIPPET = 'SET_SELECTED_SNIPPET'
export const SET_VIEW_MODE = 'SET_VIEW_MODE'
export const RESET_SNIPPET_INPUTS = 'RESET_SNIPPET_INPUTS'
export const DELETE_SNIPPET = 'DELETE_SNIPPET'
export const EDIT_SNIPPET = 'EDIT_SNIPPET'
export const SET_EDIT_MODE = 'SET_EDIT_MODE'

// ACTIONS FOR ERRORS
export const HANDLE_ERROR = 'HANDLE_ERROR'
export const RESET_ERROR  = 'RESET_ERROR'

// USER
export const HANDLE_USER = 'HANDLE_USER'

// FIREBASE DATABASE
export const PUSH_DATA_BEGIN = 'PUSH_DATA_BEGIN'
export const PUSH_DATA_SUCCESS = 'PUSH_DATA_SUCCESS'
export const PUSH_DATA_ERROR = 'PUSH_DATA_ERROR'
export const GET_DATA_BEGIN = 'GET_DATA_BEGIN'
export const GET_DATA_SUCCESS = 'GET_DATA_SUCCESS'
export const GET_DATA_ERROR = 'GET_DATA_ERROR'